whiny_config_missing: false

mack::session_id: _miki_session_id

mack::testing_framework: rspec

# Mack provides RJS support through mack-javascript gem.
# In order to have RJS support, you will need to perform the following steps:
# 1.  Uncomment the code below, and make sure that the framework is the one you want to use
# 2.  run:  rake generate:javascript
mack::js_framework: prototype

default_secret_key: 4K45YJ5ZZQRX3QYW5KBEHC5LSH7G4X7ZLZNFDN4W6PD87BE4D487D7DXGM7SRP4ETNCPWPDEHW8RYF86
