development:
  default:
    adapter: postgres
    database: miki_development
    host: localhost
    username: ruby
    password: password
    
test:
  default:
    adapter: postgres
    database: miki_test
    host: localhost
    username: ruby
    password: password

production:
  default:
    adapter: postgres
    database: miki_production
    host: localhost
    username: ruby
    password: password

# development:
#   default:
#     adapter: sqlite3
#     database: <%= File.join(Mack.root, "db", "miki_development.db") %>
#  
# test:
#   default:
#     adapter: sqlite3
#     database: <%= File.join(Mack.root, "db", "miki_test.db") %>
#  
# production:
#   default:
#     adapter: sqlite3
#     database: <%= File.join(Mack.root, "db", "miki_production.db") %>

