--- 
pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
port: 3000
chdir: /home/markbates/miki/current
max_persistent_conns: 512
environment: production
daemonize: true
address: 0.0.0.0
servers: 3
